// <auto-generated />
using ImparApp.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImparApp.Infra.Migrations
{
    [DbContext(typeof(ImparContext))]
    partial class ImparContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ImparApp.Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PhotoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Card 1",
                            PhotoId = 1,
                            Status = "Status 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Card 2",
                            PhotoId = 2,
                            Status = "Status 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Card 3",
                            PhotoId = 3,
                            Status = "Status 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Card 4",
                            PhotoId = 4,
                            Status = "Status 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Card 5",
                            PhotoId = 5,
                            Status = "Status 5"
                        });
                });

            modelBuilder.Entity("ImparApp.Domain.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Base64")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base64 = "iVBORw0KGgoAAAANSUhEUgAAABcAAAAOCAIAAABLkRCkAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEESURBVDhPhZI/CsIwFIer4OIkeADByc2xl+ghegnBzd0r6NoDuHgBB3Hq4uBWsE6C0ojY+KeNL74Q40tawze0SX4f773W6y8Cm3Dlp8e2uHgmPGuONkNyE3FYQMHOLaLQgN12/VicJQBx2iE7xKUszny066nT9SS7H0SRiDw0L2iXtDhbMBXscRWf9Sw4uYbDkhZShc4TBawoWcLmNB6Y90EkqxLMka9SqKOVn51U+et9V+URc2b1CnMCshb9okHXkZ+VoFYBQAdyLqRPpCzzvwo9ge//Ql18DIrrbYY9Qr7mI3wtiF0XtD3f9u0uzBS1IMRVGs8AUQBuC6JdL9aoyksWwRvMhyA+ywOm9QAAAABJRU5ErkJggg=="
                        },
                        new
                        {
                            Id = 2,
                            Base64 = "iVBORw0KGgoAAAANSUhEUgAAABcAAAAOCAYAAADE84fzAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAI7SURBVDhPY1Ta6POfAQewE3rN0Kx+mUGG4xtUBAF+/mNiqL2py7D2hSxUBBPgNBxk8ETtcwx8LL+hItjBkx9cDJPuq0ItYYQI/gcaCWQyQXgIADL0oOU+hvn6J1EMPnXBkqGgcSbDrO3hUBEIAPmqS/MigwT7DyAP5E6IwSAC7nJcQQAytHlGHcPnd6JgPiPLP4YNa6UY+EEW/2pkYPi9ACw+46EKQ/c9DTAbBsAuhwUBNoNrJnTADQaB/3+YGPjZpIE6FRj+sM2AijIwZMjfYShVugHlQQDYcJCL0YPAN2M7Q1nbZIZf37ihohDg542wqHf7EQab5L0Mnuk7GHYc8AVbcNdxC9wSxsevuP7LsANdDI2LZc/kGaZXLWRg/sYDEUACIIOLcuTA7M6texm2zuZgYPrJAeYzsvxh2LDQloGfFeLIEx+EGZjAQQE1GARAQcT6ix3KgwAPT0GGA9uNcRoMAu4Om+EGg4Ah33sG5tuelg0M/xkZtHg/gQVBwcPK/Jfh7GUzMN/Vg4+hKl8FzAYBbAZ7uKxnqEhrhfIgYNVzOURqkeH4zpCncIshWPIxWBIG/vN8Z2BkhBhEjMGgYAVlLhCAp/MnPzgZKm/oQXkIwAhKbkDw9fschn1L/qIY7Oe2FqfBIICSif4CA195vw9D912k9Pqrg4HhMyMD959UhmjPFVBBiMFFKe1QHqbBIIC3bMmQA6ZdZdS0C1KMFP9ggM1gEMBrOAwgW/IXGPnMjBAtuAyFAAYGAFMy3QDXGPpUAAAAAElFTkSuQmCC"
                        },
                        new
                        {
                            Id = 3,
                            Base64 = "iVBORw0KGgoAAAANSUhEUgAAABcAAAAOCAYAAADE84fzAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAABpSURBVDhPY7T1P/Kf6ScHAy0AE60MBgEmKE0TQCPD/4NJKhsOMpQRiqluOMg4iKtBgAYuRwDG/5/QRMgAb36xM3Az/2HgZP4LFWFg+PmPiTqGYwNf/7LQznAQoFFShIDhZjgkD1AIGBgAfK0ZLrSxEjMAAAAASUVORK5CYII="
                        },
                        new
                        {
                            Id = 4,
                            Base64 = "iVBORw0KGgoAAAANSUhEUgAAABwAAAARCAYAAADOk8xKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAADgSURBVEhLY3wro/KfgY6ACUrTDQxuC1kd7Bj4d21hEDh5mIF//04G9tAgqAzxgKQ4FDh3jIFJVBTKY2D4//Mnw3sVHSiPOECSD5EtAwFGdnYoi3hAtIWg4KQGwBmkIAu425sYmGSkoSKEwb8nTxm+901i+Ll6HVQEE+C0UPD8CQZGEWEoj3jw/88fhveKmlAeJsAdpKwsUAZpgJGREcrCDnBa+H36bCiLNPBz2SooCzsgKVsIPb4NZSHAO1lVKIs4QFK2AOU7SgFJFn7vnwxlQcDPxcuhLOLBaG1BZcDAAADVVTd/arIdowAAAABJRU5ErkJggg=="
                        },
                        new
                        {
                            Id = 5,
                            Base64 = "iVBORw0KGgoAAAANSUhEUgAAABcAAAAOCAYAAADE84fzAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAABGSURBVDhPY/wPBAw0AkxQmiZg6BqON8zfyapCWbiB0OPbUBYmGNhgYZKVgbJIBwQN//f4CZRFOhimqYVSMHSDhYaGMzAAAE83Eg4T1IkNAAAAAElFTkSuQmCC"
                        });
                });

            modelBuilder.Entity("ImparApp.Domain.Models.Card", b =>
                {
                    b.HasOne("ImparApp.Domain.Models.Photo", "Photo")
                        .WithOne("Card")
                        .HasForeignKey("ImparApp.Domain.Models.Card", "PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ImparApp.Domain.Models.Photo", b =>
                {
                    b.Navigation("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
